### ISSUE TITLE
New Instance: ~vern beatbump

### ISSUE THREAD

**Issue by gi-yt** [snuffyDev/Beatbump-Instances#12]
I would appreciate if you could add the ~vern beatbump instance to the instance list.
Links:
https://bb.vern.cc (Clearnet)
http://bb.vernccvbvyi5qhfzyqengccj7lkove6bjot2xhh5kajhwvidqafczrad.onion (TOR)
http://vern6inmbjzqpecx4kpkq5sln3cqqrfuxfzh4au3tpxbsfbwbnta.b32.i2p (I2P)

The service is hosted in the US on Hetzner.

**Comment by snuffyDev** [comment]
Added!
